baseURL = "https://czyt.tech/"
languageCode = "zh"
title = "è™«å­æ¨±æ¡ƒ"
theme = ["PaperMod"]
googleAnalytics = ""

[params]
	author = "czyt"
	description = "æˆ‘æ¥é—®é“æ— é¦€è¯´ï¼Œäº‘åœ¨é’å¤©æ°´åœ¨ç“¶ã€‚"
	githubUsername = "czyt"
	accent = "red"
	showBorder = true
	backgroundColor = "white"
	font = "Raleway" # should match the name on Google Fonts!
	highlight = true
	highlightStyle = "default"
	favicon = "/img/favicon.ico" 
	highlightLanguages = ["go", "c#", "dart", "bash", "swift","rust","json","xml"]
	ShowCodeCopyButtons = true
	comments = true
	ShowReadingTime = true
	ShowShareButtons = true
	ShowToc = true
	TocSide = "right"
              EnableImageZoom = true
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
[params.fuseOpts]
	isCaseSensitive= false
	shouldSort= true
	location= 0
	distance= 1000
	threshold= 0.4
	minMatchCharLength= 0
	keys= ["title", "permalink", "summary", "content"]

[params.utteranc]
	enable = true
	repo = "czyt/comments"
	issueTerm = "pathname"
	theme = "github-light"       

[[menu.main]]
    url = "/"
    name = "ğŸ Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "ğŸ™‹About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "ğŸ“šPosts"
    weight = 3

[[menu.main]]
    url = "/search/"
    name = "ğŸ”Search"
    weight = 4

[[menu.main]]
    url = "/tags/"
    name = "ğŸ”–Tags"
    weight = 5

[[menu.main]]
    url = "/links/"
    name = "ğŸ”‘Links"
    weight = 6
    
[[menu.main]]
    url = "https://github.com/czyt"
    name = "ğŸ§®Github"
    weight = 7
    
[[menu.main]]
    url = "https://czyt.tech/aicode.html"
    name = "ğŸ¤–AICode"
    weight = 8
    
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:root@czyt.tech"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/czyt/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://github.dev/czyt/blog"
    name = "fab fa-pen-clip"
    weight = 3

[[menu.icon]]
    url = "https://www.yuque.com/czyt"
    name = "fab fa-golang"
    weight = 4

[outputs]
home=["HTML","RSS","JSON"]

